version: "3"
services: 
  api:
    build:
      context: .
      dockerfile: dev.Dockerfile
    ports:
      - "3000:3001"
    links: 
      - db
      - redis
    environment: 
      REDIS_URL: redis://:${REDIS_PASSWORD}@redis:6379
      DEV_DBURL: mongodb://db:27017/report-missing-people
  db:
    image: mongo
  redis:
    image: redis
    command: redis-server --requirepass ${REDIS_PASSWORD}